version: '3.8'

services:
  amq-broker:
    image: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:latest
    container_name: amq-broker-dev-local
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      - AMQ_USER=admin
      - AMQ_PASSWORD=admin
      - AMQ_DATA=/opt/jboss/amq/data
      - AMQ_REQUIRE_LOGIN=false
      - AMQ_EXTRA_ARGS=--no-autotune --no-fsync
      - AMQ_DATA_DIR_LOGGING=true
      - AMQ_CRITICAL_ANALYZER=false
      - AMQ_EXTRA_ARGS=--force # Adicionado para forçar sobrescrita
    volumes:
      - amq-data:/opt/jboss/amq/data
      - ./broker/etc/:/home/jboss/broker/etc # Monta o diretório completo
    user: "0:0"  # root
    command: >
      bash -c "mkdir -p /opt/jboss/amq/data &&
               chown -R 1000:0 /opt/jboss/amq &&
               chown -R 1000:0 /home/jboss/broker &&
               exec /opt/amq/bin/launch.sh"
    networks:
      - amq-network

networks:
  amq-network:
    driver: bridge

volumes:
  amq-data: