spring:
  application:
    name: spring-artemis-producer

  artemis:
    broker:
      url: tcp://localhost:61616
    user: admin
    password: admin

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8090